# Generated by Django 5.2.7 on 2025-10-24 02:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(max_length=255)),
                ('athlete_photo', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('country_flag', models.URLField(blank=True, null=True)),
                ('sport', models.CharField(choices=[('swimming', 'Swimming'), ('athletics', 'Athletics'), ('gymnastics', 'Gymnastics'), ('basketball', 'Basketball'), ('football', 'Football'), ('tennis', 'Tennis'), ('boxing', 'Boxing'), ('weightlifting', 'Weightlifting')], max_length=50)),
                ('biography', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
