# Generated by Django 5.2.5 on 2025-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="athletes",
            name="achievements",
        ),
        migrations.RemoveField(
            model_name="athletes",
            name="country_flag",
        ),
        migrations.RemoveField(
            model_name="athletes",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="athletes",
            name="height",
        ),
        migrations.RemoveField(
            model_name="athletes",
            name="weight",
        ),
        migrations.AlterField(
            model_name="athletes",
            name="athlete_photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="athletes",
            name="sport",
            field=models.CharField(max_length=100),
        ),
    ]
