# Generated by Django 5.2.5 on 2025-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0002_remove_athletes_achievements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athletes",
            name="athlete_photo",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
