# Generated by Django 5.2.5 on 2025-10-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_section", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="forum",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum_section.forum",
            ),
        ),
    ]
