# Generated by Django 5.2.6 on 2025-10-14 11:45

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('athletics', 'Athletics'), ('swimming', 'Swimming'), ('a', 'A')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('dislike_user', models.ManyToManyField(blank=True, related_name='disliked_articles', to=settings.AUTH_USER_MODEL)),
                ('like_user', models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
