# Generated by Django 5.2.7 on 2025-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('athletics', 'Athletics'), ('swimming', 'Swimming'), ('b', 'B'), ('a', 'A')]),
        ),
    ]
