# Generated by Django 5.2.7 on 2025-10-23 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_thumbnail'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sports'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('athletics', 'Athletics'), ('archery', 'Archery'), ('artistic_gymnastics', 'Artistic Gymnastics'), ('artistic_swimming', 'Artistic Swimming'), ('badminton', 'Badminton'), ('baseball_softball', 'Baseball/Softball'), ('basketball', 'Basketball'), ('beach_volleyball', 'Beach Volleyball'), ('boxing', 'Boxing'), ('canoe_slalom', 'Canoe Slalom'), ('cycling_road', 'Cycling Road'), ('diving', 'Diving'), ('fencing', 'Fencing'), ('football', 'Football'), ('handball', 'Handball'), ('hockey', 'Hockey'), ('judo', 'Judo'), ('karate', 'Karate'), ('marathon_swimming', 'Marathon Swimming'), ('rowing', 'Rowing'), ('rhythmic_gymnastics', 'Rhythmic Gymnastics'), ('sailing', 'Sailing'), ('shooting', 'Shooting'), ('swimming', 'Swimming'), ('table_tennis', 'Table Tennis'), ('taekwondo', 'Taekwondo'), ('trampoline_gymnastics', 'Trampoline Gymnastics'), ('triathlon', 'Triathlon'), ('water_polo', 'Water Polo'), ('weightlifting', 'Weightlifting'), ('wrestling', 'Wrestling')]),
        ),
    ]
