# Generated by Django 5.2.7 on 2025-10-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_related_sport_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_sport',
        ),
    ]
