# Generated by Django 5.2.7 on 2025-10-20 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=255)),
                ('sport_img', models.URLField(blank=True, null=True)),
                ('sport_description', models.TextField()),
                ('participation_structure', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=20)),
                ('sport_type', models.CharField(choices=[('water_sport', 'Water Sport'), ('strength_sport', 'Strength Sport'), ('athletic_sport', 'Athletic Sport'), ('racket_sport', 'Racket Sport')], default='athletic_sport', max_length=20)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('country_flag_img', models.URLField(blank=True, null=True)),
                ('first_year_played', models.IntegerField(default=0)),
                ('history_description', models.TextField()),
                ('equipment', models.TextField()),
            ],
        ),
    ]
