# Generated by Django 5.2.7 on 2025-10-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='participation_structure',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('both', 'Individual & Team')], default='individual', max_length=20),
        ),
    ]
