# Generated by Django 5.2.7 on 2025-10-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_sports_participation_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='sport_type',
            field=models.CharField(choices=[('water_sport', 'Water Sport'), ('strength_sport', 'Strength Sport'), ('athletic_sport', 'Athletic Sport'), ('racket_sport', 'Racket Sport'), ('ball_sport', 'Ball Sport'), ('combat_sport', 'Combat Sport'), ('target_sport', 'Target Sport')], default='athletic_sport', max_length=20),
        ),
    ]
