# Generated by Django 5.2.5 on 2025-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_alter_sports_sport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sports",
            name="country_flag_img",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
