# Generated by Django 5.2.5 on 2025-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0004_alter_sports_country_flag_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sports",
            name="country_flag_img",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
