# Generated by Django 5.2.7 on 2025-10-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpoll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='option1_votes',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='option2_votes',
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='landingpoll.pollquestion')),
            ],
        ),
    ]
