# Generated by Django 5.2.7 on 2025-10-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
